### ISSUE TITLE
[Question] Availability of environments in the paper

### ISSUE THREAD

**Issue by VincentYu68** [NVIDIA-Omniverse/Orbit#10]
Hi, there seems to be several environments missing in the repo right now compared to the paper. I'm wondering if they are not in the orbit_env directory, or they are yet to be released? If latter, is there any timeline on when they'll be available?

Thanks!

**Comment by animesh-garg** [comment]
Thanks for the note.
Many of the environments in the paper are listed here
https://isaac-orbit.github.io/orbit/source/features/environments.html

The rigid body environments and legged robot environments should be released shortly. 

The soft object environments are available but since they do not have support for tensorAPI, using them for RL workflow on GPU is not yet possible. 
The new API is under development. Hence, the soft object environments will be transferred to support the new API to minimize deprecation due to change of soft-body tensorAPI.

We are sharing the development pipeline (along with estimated timelines)
https://isaac-orbit.github.io/orbit/source/refs/roadmap.html
