### ISSUE TITLE
[Question] How to add a RigidContactView into the scene?

### ISSUE THREAD

**Issue by 2361098148** [NVIDIA-Omniverse/Orbit#110]
### Question

I find that the RigidContactView.initialize could not add the RigidContactView to the scene, which caused the simulation breakdown. What should I do to implement the `scene.add(RigidContactView)` function. It seems that there is no scene created directly

**Comment by 2361098148** [comment]
The same problem could be seen:[link](https://github.com/NVIDIA-Omniverse/Orbit/issues/97#issuecomment-1644532310)
[link](https://github.com/NVIDIA-Omniverse/Orbit/issues/102#issuecomment-1668904159)

**Comment by noibar** [comment]
I had the same problem. I was able to solve it so I hope this would help:
In order to initialize RigidPrimView with track_contact_forces=True and the contact sensors to work without causing errors, you have to make sure that your initialization process contains all of the necessary steps in the right order.
You can see the expected order in this [example](https://docs.omniverse.nvidia.com/isaacsim/latest/ext_omni_isaac_core.html) and in the implementation of the World class. 

The initialization flow should be:
1. Create your views: ArticulationView, RigidPrimView
2. simulation_context.reset(soft=False)
3. Initialize articulations and rigid prim views with .initialize()

If you are working with SimulationContext (like in orbit examples) without a World object, you have to call view.initialize() directly, but you have to do it only after sim.reset() is called.
(In the rigid_contact_view.py example, the scene.add() registers the contact view and causes the view initialize() to be called later)

**Comment by 2361098148** [comment]
Thanks a lot!!! That works.
