### ISSUE TITLE
[Question] ArticulatedObject Example

### ISSUE THREAD

**Issue by MarcelTorne** [NVIDIA-Omniverse/orbit#45]
### Could we have an example of how to create an articulated object?

In your Robotic Workflows/Reinforcement learning video (https://isaac-orbit.github.io/) you have an example of the robot opening a drawer, we also see you have an ArticulatedObject class, however we did not find any example of how to create such an object. It would be really appreciated if you could release this example, and also a sample .usd file of an articulated object.

Thank you very much in advance

**Comment by Mayankm96** [comment]
Hi,

We apologize for the delay in answering. A lot changed since this question was asked. 

We now have an example of Franka's arm opening a cabinet: https://github.com/NVIDIA-Omniverse/orbit/tree/main/source/extensions/omni.isaac.orbit_tasks/omni/isaac/orbit_tasks/manipulation/cabinet

Please re-open the issue if it is still unresolved.
