### ISSUE TITLE
[Bug Report] Teleoperation demo script does not work

### ISSUE THREAD

**Issue by ADebor** [NVIDIA-Omniverse/Orbit#46]
### Describe the bug

The teleop example (source/standalone/environments/teleoperation/teleop_se3_agent.py) fails. When launched using the --cpu option or not, the script runs, but I'm not able to control the robot using the keyboard. I simply launch it in the terminal and press keys on my keyboard, making them printed in this same terminal, but not moving the robot in the simulator. When pressing keys in the simulator, 'K' does toggle the gripper (which is expected), but pressing other keys simply selects different modes in the left panel of the simulator.

### Steps to reproduce

Run teleoperation demo in [API Demos](https://isaac-orbit.github.io/orbit/source/setup/sample.html#api-demos):

`./orbit.sh -p source/standalone/environments/teleoperation/teleop_se3_agent.py --task Isaac-Lift-Franka-v0 --num_envs 1 --cpu --device keyboard`

No error in the terminal:

![image](https://user-images.githubusercontent.com/72311549/229116157-85463ee4-83f2-4646-b29d-5044650b0519.png)

### System Info

- Commit: [bea049b](https://github.com/NVIDIA-Omniverse/Orbit/commit/bea049b3fefc1adb6366836e4be6b7097c86daa0)
- Isaac Sim Version: 2022.2.1
- OS: Ubuntu 20.04
- GPU: RTX 3060
- CUDA: 12.0
- GPU Driver: 525.85.05

### Additional context

Bug first mentioned [here](https://github.com/NVIDIA-Omniverse/Orbit/issues/1#issuecomment-1491606297). Potential cause of the error mentioned [here](https://github.com/NVIDIA-Omniverse/Orbit/issues/1#issuecomment-1491772758).

### Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have checked that the issue is not in running Isaac Sim itself and is related to the repo

**Comment by Mayankm96** [comment]
Hi! I'm sorry for not getting back to you sooner.

I ran the command line argument you provided, and it seems the robot doesn't move. However, if you press `K`, the gripper is opening/closing. This means that the keyboard's sensitivity needs to be altered (somehow different keyboards have different latencies so their sensitivity changes).

If you run the following, you will notice the robot move:

```bash
./orbit.sh -p source/standalone/environments/teleoperation/teleop_se3_agent.py --task Isaac-Lift-Franka-v0 --num_envs 1 --cpu --device keyboard --sensitivity 10
```

Also, it is important to note that for the keyboard interface to work, the active window should be the Isaac Sim GUI. Otherwise, the keyboard callbacks (through the application) won't work. This isn't necessary when using Spacemouse as over there we directly read from the device port.
